import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
// comment
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

// Generate metadata using appSettingsApi base URL configuration
export async function generateMetadata() {
  let faviconUrl = "/img/favi.png"; // Default favicon

  try {
    // Use the same base URL configuration as appSettingsApi
    const baseUrl = `${process.env.NEXT_PUBLIC_BASE_URL}/settings`;
    const response = await fetch(`${baseUrl}/`, {
      next: { revalidate: 60 }, // Revalidate every 60 seconds
      credentials: "include", // Match appSettingsApi config
    });

    if (response.ok) {
      const data = await response.json();
      if (data?.success && data?.data?.favicon) {
        faviconUrl = data.data.favicon;
      }
    }
  } catch (error) {
    // Fall back to default favicon if API call fails
  }

  return {
    title: {
      template: "Besiks - %s",
      default: "Besiks",
    },
    description: "Generated by create next app",
    icons: {
      icon: faviconUrl,
      apple: faviconUrl,
    },
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <StoreProvider>
          {children}
          <Toaster
            position="top-right"
            richColors
            closeButton
            duration={4000}
          />
        </StoreProvider>
      </body>
    </html>
  );
}
